name: clima_pro
description: ClimaPro - Instalaci√≥n y Mantenimiento HVAC
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  url_launcher: ^6.3.0
  image_picker: ^1.0.0
  firebase_storage: ^12.0.0

  cupertino_icons: ^1.0.8
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  firebase_messaging: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true